apiVersion: batch/v1
kind: CronJob
metadata:
  name: scoreboard-scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scoreboard-scheduler
            image: allenlo83/scoreboard-app:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - php /var/www/artisan schedule:run
          restartPolicy: OnFailure