name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  ENV_FILE: ${{ vars.ENV_FILE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure kubectl
      run: |
        echo "$ENV_FILE" > .env
        echo "REVERB_APP_ID=${{ secrets.REVERB_APP_ID }}" >> .env
        echo "REVERB_APP_KEY=${{ secrets.REVERB_APP_KEY }}" >> .env
        echo "REVERB_APP_SECRET=${{ secrets.REVERB_APP_SECRET }}" >> .env
      
    - name: Build Docker images
      run: |
        docker build -t $DOCKER_USERNAME/scoreboard-reverb:latest -f Dockerfile.reverb .
        docker build -t $DOCKER_USERNAME/scoreboard-nginx:latest -f Dockerfile.nginx .
        docker build -t $DOCKER_USERNAME/scoreboard-app:latest -f Dockerfile .
        
    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
    - name: Push images to Docker Hub
      run: |
        docker push $DOCKER_USERNAME/scoreboard-reverb:latest
        docker push $DOCKER_USERNAME/scoreboard-nginx:latest
        docker push $DOCKER_USERNAME/scoreboard-app:latest
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Configure kubectl
      run: echo "$KUBE_CONFIG" > kubeconfig.yaml

    - name: Create Kubernetes Secrets
      run: |
        kubectl --kubeconfig=./kubeconfig.yaml delete secret laravel-secrets --ignore-not-found
        kubectl --kubeconfig=./kubeconfig.yaml delete secret mysql-secrets --ignore-not-found
        kubectl --kubeconfig=./kubeconfig.yaml delete secret reverb-secrets --ignore-not-found
        kubectl --kubeconfig=./kubeconfig.yaml create secret generic laravel-secrets --from-literal=app-key=${{ secrets.APP_KEY }}
        kubectl --kubeconfig=./kubeconfig.yaml create secret generic mysql-secrets --from-literal=root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} --from-literal=username=${{ secrets.MYSQL_USERNAME }} --from-literal=password=${{ secrets.MYSQL_PASSWORD }}
        kubectl --kubeconfig=./kubeconfig.yaml create secret generic reverb-secrets --from-literal=app-id=${{ secrets.REVERB_APP_ID }} --from-literal=app-key=${{ secrets.REVERB_APP_KEY }} --from-literal=app-secret=${{ secrets.REVERB_APP_SECRET }}
      
    - name: Update Kubernetes deployments
      run: |
        kubectl --kubeconfig=./kubeconfig.yaml apply -f kubernetes/laravel-k8s.yaml
